import Head from 'next/head';
import { Header, About, WhatWeDo, HowWeDo, WhoWeAre, Contacts, Navbar } from "../sections";
import localFont from '@next/font/local';
const myFont = localFont({ src: '../public/fonts/Suisse.woff2' })


export default function Home() {
    return (
        <>
            <Head>
                <title>Aretta. Marketing agency</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={`${myFont.className}`} >
                <Navbar />
                <Header />
                <About />
                <WhatWeDo />
                <HowWeDo />
                <WhoWeAre />
                <Contacts />
            </main>
        </>
    )
}
